### ISSUE TITLE
Multisite issue with main site

### ISSUE THREAD

**Issue by JonasBrand** [benbalter/wp-document-revisions#111]
When using WP Document Revisions in a multisite installation, there are issues with the uploads folder setting when using the plugin both on the main site (usually site with ID = 1) and on other sub-sites.

This is how the uploads folder is set by default for multisite installations:
_Your first site on a fresh install will put uploaded files in the traditional location of /wp-content/uploads/, however all subsequent sites on your network will be in the /wp-content/uploads/sites/ folder, in their own subfolder based on the site number, designated by the database. These files will be accessible via that URL._
Source: https://codex.wordpress.org/Multisite_Network_Administration#Uploaded_File_Path

When I set the uploads path in the WP Document Revisions network-wide setting to
"[PATH]/wp-content/uploads", it will work on the main site but not on other subsites.

When I set it to "[PATH]/wp-content/uploads/sites/%site_id%/", it won't work on the main site but on the other subsites.

**Comment by JonasBrand** [comment]
Right now I fixed it like this

`
		if( is_multisite() && is_main_site()) {
			return $defaults['basedir'];
		}`
in document_upload_dir().

Do you have any better idea then just using the default basedir for the main site?

**Comment by benbalter** [comment]
I believe `is_network_admin` in https://github.com/benbalter/wp-document-revisions/blob/master/includes/class-wp-document-revisions.php#L1032 should be `is_main_site`. Does that solve the problem?

**Comment by JonasBrand** [comment]
No, that won't solve the problem. As far as I understand, the ´!is_network_admin´ is required to avoid that the %site_id% is replaced when you're on the Network Admin screen.

See my suggestion above. I would think that covers everything.

**Comment by benbalter** [comment]
@JonasBrand that last option works for me! If you're willing/able to submit a pull request, I'd be glad to review and merge.
