### ISSUE TITLE
404 Errors with latest version in Multisite environment

### ISSUE THREAD

**Issue by julianmatz** [benbalter/wp-document-revisions#117]
With the latest update, WP Document Revisions seems to have stopped working in my MU setup. Documents appear to load on the main site, but not on any others. The plugin is Network Activated. What seems to happen for all document links is that a trailing slash is added to the end of the URL (via redirect) and a 404 page is served. When downgrading to version 3.0.1, it works.

Permalinks are set to post name.

**Comment by benbalter** [comment]
@JonasBrand could this be related to #113 / #111?

**Comment by JonasBrand** [comment]
I don't think so. I'll run some tests on the latest version to see if I can replicate the issue.

@julianmatz: Which "Document Upload Directory" do you have set in the network-wide configuration (Network Admin -> Settings- > Network Settings -> Document Settings)? Should be _[YOURPATH]/wp-content/uploads/sites/%site_id%_ for a normal setup.

**Comment by JonasBrand** [comment]
I also see the issue julianmatz describes with the latest version 3.1.1.
On the subsite (not on the main site), the HTTP request to /documents/file.zip is answered with a redirect to /documents/file.zip/ (via location header) and that leads to a 404 error. So it rather looks like a redirect rule issue to me...

**Comment by julianmatz** [comment]
@JonasBrand I had left the Document Upload Directory set to its default, but after I noticed the issue, I changed it to:

`/home/[****]/public_html/wp-content/uploads/documents`

I also changed the Document Slug from "documents" to "docs" and refreshed the Permalink Settings, but this didn't make a difference.

I got the same results with all.

I'm not too sure if it's a redirect issue. One document did load for me once, even with the trailing slash. I also tried changing the permalink structure from `/%postname%/` to `/%postname`. This prevented the redirect, but I still got the 404.

**Comment by benbalter** [comment]
I believe https://github.com/benbalter/wp-document-revisions/pull/119 may fix this. Please try version 3.1.2.

**Comment by benbalter** [comment]
Per https://wordpress.org/support/topic/permalinks-not-working-after-upgrade-from-2-2-0-to-3-1-1/#post-10020203, I believe this is fixed, but please comment/reopen if that is not the case.

**Comment by JonasBrand** [comment]
No, this issue is unfortunately not fixed with the new version 3.1.2. Please re-open - I don't seem to have the permission.

**Comment by julianmatz** [comment]
Please let me know if you'd like me to test.
