### ISSUE TITLE
404 errors when trying to view files

### ISSUE THREAD

**Issue by bmattiello2017** [benbalter/wp-document-revisions#118]
When trying to view documents with permalinks set to anything besides plain I get the 404 error.
for now to allow users to view documents which is critical I have to leave the permalinks setting to simple which is not ideal. All other pages etc now look terrible. Is there a solution to this and if not are you working on one?

Thanks

**Comment by benbalter** [comment]
Please see https://github.com/benbalter/wp-document-revisions/issues/117.

**Comment by bmattiello2017** [comment]
None of that has helped me 
I am on a stand alone version of Wordpress
Is there something else I can try?

Thanks

**Comment by bmattiello2017** [comment]
We have been using your plugin for several years with no issues!
I updated to 3.1.2 and now it displays the pdf window with no content in it? I am on a stand alone nginx server and running the newest version of your plugin. the document slug path is set to the default I suppose which is https://www.paint.org/documents/2018/03/example-doc.pdf. It was working on an Apache server but since moving to WpEngine on an nginx server no go. I am at my wits end and would greatly appreciate your help at helping me resolve this issue. I have numerous users not able to view these documents. Thanks in advance

**Comment by bmattiello2017** [comment]
Never mind I just figured it out!

**Comment by aaronhb** [comment]
What did you do to fix as I am having the same issue for all documents I create. I tried changing the path under the document settings but nothing works and shows a 404.

**Comment by aaronhb** [comment]
> Never mind I just figured it out!

What was your fix on WPEngine? I am having same issue and no documents work and I get 404 no matter what I change.
