### ISSUE TITLE
Error re. array_key_exists

### ISSUE THREAD

**Issue by tbnv** [benbalter/wp-document-revisions#135]
Hello.
This error appears in front-end since v3.2.
I reverted back to v3.1.2.

```
Warning
: array_key_exists() expects parameter 2 to be array, null given in
[path]/wp-content/plugins/wp-document-revisions/includes/class-wp-document-revisions.php
on line
1395
```

**Comment by benbalter** [comment]
https://github.com/benbalter/wp-document-revisions/blob/master/includes/class-wp-document-revisions.php#L1394-L1398 is the relevant line. 

I'm not sure why `$wp_query->query_vars` would be null, but easy enough to guard against it.

What version of WordPress are you using?

**Comment by tbnv** [comment]
We're using WP 5.0.3.

The error also appears on the front page of the website, even though there is no call to a document monitored by the plugin there.

**Comment by tbnv** [comment]
I see you applied the fix, thanks.
Any idea the it'll be pushed to the WP repo?

**Comment by tbnv** [comment]
Hi!

There is still an error about this when debug mode is enabled:

```
 Notice: Trying to get property 'query_vars' of non-object in [path]/wp-content/plugins/wp-document-revisions/includes/class-wp-document-revisions.php on line 1395
```
