### ISSUE TITLE
Exclude non-functional files from the Composer package and WordPress.org build

### ISSUE THREAD

**Issue by johnbillion** [benbalter/wp-document-revisions#141]
### Describe the bug

The package that's made available to Composer via Packagist, and the package that's committed to the WordPress.org Plugin Directory contains all the non-functional files that shouldn't typically be distributed. For example, the following directories shouldn't be part of the built package:

* `bin`
* `script`
* `tests`

### Steps to reproduce the behavior

1. Go to https://wordpress.org/plugins/wp-document-revisions/ and download the plugin - or - fetch the plugin via `composer install benbalter/wp-document-revisions`
2. Observe that the directories listed above are included in the package

**Comment by benbalter** [comment]
@johnbillion good point. Would you be willing to submit a PR that removes these files and adds the paths to `.gitignore` to prevent them from being recommitted on update?
