### ISSUE TITLE
wp-document-revisions not working with admin-taxonomy-filter plugin, does not filter

### ISSUE THREAD

**Issue by PeterM-9** [benbalter/wp-document-revisions#207]
Sorry, I was on the code cookbook page and erraneously posted the issue there. So here I repost in the correct project.
### Describe the bug
I linked additional custom taxonomies to the documents custom type and need the ability to filter by those taxonomies.
I used the custom post types plugin to create two taxonomies (doctype and docyear) and linked them to the documents post type. doctype is hierarchical, docyear is not. The custom taxonomies show up in the table as columns all right.
But I spent days now to get filters for those custom taxononies to work in the documents admin screen. I'd like to use the admin taxonomy filter for the purpose and I see the dropdowns created next to the workflow and owner dropdowns, but they are not functional. Selecting a term from the custom drop downs and clicking the "filter" button will reset the dropdown to the "show all" state and leave the table unfiltered. Any help for resolving that issue is highly appreciated. Thanks a lot

### Expected behavior
Selecting an entry in the custom taxonomy filter and clicking the Filter button will filter the table of documents to only those having the selected taxonomy term.

**Comment by NeilWJames** [comment]
There is no bug that I can see in WP Document Revisions.

@PeterM-9 ,
I have an existing production site. It has a number of plugins including WP Document Revisions and Simple Taxonomy Refreshed used for defining my custom taxonomies.

I installed the plugin Admin Taxonomy Filter. and set it for my custom taxonomy on documents.

It works as expected. (It also did on my Development site - but it has a heavily modified version of WP Document Revisions and I wanted to be sure.)

Please find the following information for your doctype taxonomy:
1. What is its query_var value? (By default it will be the taxonomy slug, but you could changed it.
2. Find a term of this taxonomy that you have linked to a document.

Assume these are doctype and fred; and your site URL is http://site.com/

Enter this into your browser:

`http://site.com/?doctype=fred`

Do you retrieve your document (perhaps with others)?

If you do not then this standard WP processing has some issue. This is the same standard processing that used to retrieve your documents in the documents list.

Note that this WP_Query processing requires that your taxonomy MUST be publicly_queryable.

Hope this is of use,
Neil James

**Comment by PeterM-9** [comment]
Thanks Neil for the good explanation. I tried to debug my site along your tipps, but don't get the expected results.
a) I build my custom taxonomy with "Custom post types" plugin and have linked it to the "Documents" post type. I see no option in the plugin to set the publishing status of a taxonomy so for the moment I assume it is public.
b) In the term list of my taxonomy I see always zero count, while the "workflow_state" taxonomy shows the correct values for count. This seems to be caused by my documents being private and this has to remain like that. I do not want to surface my documents in the front end.
Before I now dig deeper into the relations between all the plugins (which might go beyond my capability), can you point me to a method to add custom filter drop downs to the wp-document-revisions which work with private documents?
Thanks for your insights.
Peter

**Comment by NeilWJames** [comment]
@Peter,
You are correct that taxonomies are essentially public - strictly that there is no status associated with them.

You will have seen that I have uploaded a new version of my plugin last night - although this really ought be put against there.

This has added two new tabs to the taxonomy parameters. 

One is to add the taxonomy to the admin list for selected post types.

The other is to modify the Term count. There are two options. The first is essentially the same as is used in WP Document Revisions, which counts posts of all statuses except Trash and, of course, Auto-Draft. The second allows you to choose which statuses you want.

Hopefully this will meet your needs.

If you have further questions/issues when using Simple Taxonomy Refreshed, please raise a support issue against it.

Hope this is of use,
Neil

**Comment by NeilWJames** [comment]
@benbalter,
Within the plug-in, there is code to modify the counts for Workflow State to include all non-deleted statuses.
Peter has created another taxonomy and would like the same method of doing the term counts.
You have code to do this in the plug-in (register_term_count_cb), but it is currently non-operative.
Its intent is to modify all document-only taxonomies that use the default method (Published only) of counting to use your plug-in method.
I can easily fix it. I would provide a filter for existing users to amend the list of taxonomies and retain existing functionality. 
Equally they can set the callback to be `_update_post_term_count` and will invoke the default module.

Regards,
Neil James

**Comment by PeterM-9** [comment]
Hi Neil,
thanks for the new version of your plugin, works overall well. I have a issue with the term count in one taxononomy but not in another one. However, I raise that in your plugin support area. The combo "Simple Taxonomy Refreshed"/"WP Document Revisions" does what we need, any additional Admin Filter plugin is not necessary. Perfect! Thanks a lot.

**Comment by PeterM-9** [comment]
Since it turned out, the problem arose from the "custom post types" plugin and can therefor not be solved by WP document revisions, I close the issue now.
