### ISSUE TITLE
Lower expiration header

### ISSUE THREAD

**Issue by benbalter** [benbalter/wp-document-revisions#38]
Or perhaps make an option/filter.

see http://wordpress.org/support/topic/documents-not-updating-on-all-computers?replies=5

**Comment by jeremyfelt** [comment]
We applied a related change as a hotfix in our production environment. I'll spend some more time looking at a more appropriate answer for this and submit as a pull request. I think a shorter default with a filter likely makes sense.

https://github.com/washingtonstateuniversity/wp-document-revisions/pull/2
