### ISSUE TITLE
WP Search Function not working

### ISSUE THREAD

**Issue by rlburkey** [benbalter/wp-document-revisions#64]
Good Afternoon!

So far I love this plugin, however, when I use the WP search functionality, if there is a document in the results, the search page's layout is broken. You can see what I mean at the following links:

Search page that works - http://dev.170frontdesign.com/intranet/?s=It
 Search page that is broken - http://dev.170frontdesign.com/intranet/?s=month

Any ideas on what's going on?

Thanks Much!
 ~R

**Comment by ctarazona** [comment]
Hi,

I'm also been having the issue of not getting any search results with WP's built-in search.  I'm not looking for search within files but just names and meta (anything WP should know about).  We tried using "Better Search" but it didn't seem to help.

Any ideas?  Thanks!

Carlos

**Comment by benbalter** [comment]
Is this problem still occurring on the latest version? If so, please comment or re-open the issue.
