### ISSUE TITLE
Revision history the same document version

### ISSUE THREAD

**Issue by bkuhl** [benbalter/wp-document-revisions#66]
This morning I uploaded a new version of a document, and it seems older version was overwritten with the latest version that I uploaded.

http://home.biblebowl.net/documents/2014/03/rule-book-beginner.pdf

http://home.biblebowl.net/documents/2014/03/rule-book-beginner-revision-2.pdf

Both documents say "2014-2015" on the top right corner, whereas the older one ("revision 2"), if I understand correctly should indicate "2013-2014".  The last modified time also shows "3 hours ago" for both revisions.

![screen shot 2014-05-24 at 11 10 16 am](https://cloud.githubusercontent.com/assets/524933/3075286/ccab5bae-e36e-11e3-84f9-6466f9956527.png)

RSS feed is here: http://home.biblebowl.net/documents/2014/03/rule-book-beginner.pdf/feed/?key=qEs5T0a4y1RRMeSQMtVvQit6Y7cU7xJP

**Comment by benbalter** [comment]
@bkuhl is this problem still occurring on the latest version? If so, please re-open the issue.
