### ISSUE TITLE
Looking for contributors / maintainer

### ISSUE THREAD

**Issue by benbalter** [benbalter/wp-document-revisions#68]
The plugin's a solid plugin with a decent user base, but it could use some <3 from a WordPress developer or two. 

Interested in helping out? Consider [tackling an open issue](https://github.com/benbalter/WP-Document-Revisions/issues), or reply below if you're interested in becoming a project maintainer.

**Comment by jeremyfelt** [comment]
Hi @benbalter, thanks for the excellent plugin! We've been using it for the last couple years at Washington State University and it's been very handy at filling some of the gaps WordPress has with document management. I'm interested in providing whatever support I can in maintaining the project.

I'm a big fan of plugins that provide a solution and then just work. I don't think there's too much that really needs to be done, but it'd be nice to tackle these things:

* Add PHP code sniffing with [WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards). This will create some code churn right away, but will help (1) catch some minor unknown bugs and (2) update code formatting to align with what the WordPress community has settled on in the last few years. This makes it easier to accept code changes from new contributors.
* Determine how to handle Webdav. I'm guessing that it's not used too much as it requires special server configuration, but I can also imagine it being very useful for anyone that has it configured. It'd be interesting to think through what it looks like to extract this code as another plugin. (Or just let it be) See #79, #77.
* Work through the current issues and close/progress.
* Poke around for areas that may enjoy an update. :)

**Comment by benbalter** [comment]
>  it's been very handy at filling some of the gaps WordPress has with document management. I'm interested in providing whatever support I can in maintaining the project.

Wow. That's great to hear (and thanks for the kind words). I'll take as much or as little help as you can offer, including transferring ownership. Before I do, I'd like to spend a few cycles myself getting the project someplace I can proudly ask another developer to maintain.

> I'm a big fan of plugins that provide a solution and then just work.

That's a great way to put it. You and in agreement. :smile:

> Add PHP code sniffing with WPCS

Great suggestion. I thought I had done this recently, but it turns out it was for another plugin I maintain. I'd hate to ask you to maintain a project that isn't up to standards. I should have a block of time Sunday, and can take an initial pass at adding WPCS to get a sense of how big the delta is.

> Determine how to handle Webdav... think through what it looks like to extract this code as another plugin

To be honest, I regret adding it. I don't use the feature, can't test it easily, and am not in a position to maintain the code. If you don't need the feature for your use case, I'm fine dropping support entirely, unless someone who needs the functionality is in favor of maintaining a separate plugin.

> Work through the current issues and close/progress

I can open issues for the above so that they're in the backlog.

> Poke around for areas that may enjoy an update.

I'll also get 2.2.0 out, since the project deserves an update, which I suspect may bring some attention this way.
