### ISSUE TITLE
Webdav filter usage further step needed

### ISSUE THREAD

**Issue by purecreative** [benbalter/wp-document-revisions#77]
The document_revisions_enable_webdav filter is fine for hiding the Edit on Desktop button, but currently the code is still doing things like checking for authorisation.

On line 139 on wp-document-revisions.php there is code:

```
    if ( in_array( $request_method, $webdav_methods )  || ( in_array( $request_method, $private_checked_methods ) && $this->is_webdav_client() ) ) {
        $this->basic_auth();
    }
```

I've changed this to:

```
    if ( in_array( $request_method, $webdav_methods ) && apply_filters( 'document_revisions_enable_webdav', true ) || ( in_array( $request_method, $private_checked_methods ) && $this->is_webdav_client() && apply_filters( 'document_revisions_enable_webdav', true ) ) ) {
        $this->basic_auth();
    }
```

This stops unwanted credentials prompts from Office software if you aren't using a Webdav server and using Document Revisions to serve up your Office files.

**Comment by benbalter** [comment]
I'd almost prefer to [drop webdav support entirely](https://github.com/benbalter/wp-document-revisions/issues/79), in favor of ease of maintainability.
