### ISSUE TITLE
Drop Webdav support

### ISSUE THREAD

**Issue by benbalter** [benbalter/wp-document-revisions#79]
Any objections? Anyone interested in taking a pass?

**Comment by ThreeMcc** [comment]
Could it be an add on code... as in leave action and filter hooks in the code in case some others want it?  Then leave the code example in the code cookbook.

I really like desktop integration through WebDav, but I am having a hard time getting it to save - so for the time being I am planning to use CSS to just hide the "Edit on Desktop" button until I can get it working properly.

So I personally think it would be better if people could choose to add it later in a dev environment, then publish the changes after the server and everything is setup properly to handle it...  Those that don't need it, never have to add it at all...  As long as the hooks are there and the cookbook has some initial code to get us going, who can complain...

Just a thought, not sure how hard that would be to implement.  

Also, Awesome work!  Thank You!  
Very flexible design, just took a minute to figure out how to get all the security stuff working right.
The initial release of the "Provider Portal", for our clinic, is set to launch March 1st.

**Comment by benbalter** [comment]
Per #68, bumping this discussion. Would anyone be interested in maintaining webdav support as a small, optional plugin?
