### ISSUE TITLE
Permissions not correct in a multi-site environment

### ISSUE THREAD

**Issue by gdginc** [benbalter/wp-document-revisions#80]
When installed as a plugin with WordPress Network Mode enabled, even a Site Admin does not have access to the Documents menu.

This makes the entire Documents system inaccessible for all users except for the SuperAdmin role.

Access permissions need to be set so they are available to the Admin role.  (Would be nice if minimum access could be set on a per site basis.)

**Comment by jeremyfelt** [comment]
@gdginc Do you have the plugin network activated or individually for each site? A [series of capabilities](https://github.com/benbalter/wp-document-revisions/blob/9b6ed178c0735fd7c1073d8df2b4cd3276802851/wp-document-revisions.php#L1472) are setup for the plugin on initial site activation. We're using it a multi-network environment via individual site activation with no issues, though I have not tried with network activation. If nothing else, you can duplicate this list of caps in another plugin to ensure they're available.

**Comment by gdginc** [comment]
We had it network activated so that it would be instantly available to all our users.  We deactivated it and then individually activated it on a target site.  It suddenly became available for appropriate users.

So there’s an issue with the plugin when Network Activated where it doesn’t propagate permissions properly but will work if individually activated.  Kind of a pain to administrate that way so I hope you’re able to apply a fix.

Thanks!
