### ISSUE TITLE
Download will only work with default Permalink settings

### ISSUE THREAD

**Issue by mjburrows** [benbalter/wp-document-revisions#82]
Hi,
I have a small issue where I cannot download any document unless Permalink settings are default. 

With any other Permalink setting, downloads will fail with 404 error. Has anyone else experienced this?

Thanks
--Maurice--

**Comment by tundrastudio** [comment]
Same problem but I noticed something.
My wordpress with wp document revisions on WAMP, XAMPP and ZWAMP on windows works flawless, links in all forms work BUT on linux server LAMP it does not, only with default permalinks.

Also tried to transfer same copy of wordpress from windows to linux, and works on win and not on linux.
