### ISSUE TITLE
Broken xlsx file

### ISSUE THREAD

**Issue by Kristian88** [benbalter/wp-document-revisions#84]
Hi

When I run this on a HTTP site everything works fine.
However when i try to download a XLSX file on a HTTPS site
it is broken.

Any suggestions?

**Comment by Kristian88** [comment]
I found out that this happens because of the plugin WPML.
Any idea why??

**Comment by benbalter** [comment]
@Kristian88 is this problem still occurring on the latest version? If so, please re-open the issue.
