### ISSUE TITLE
Document Upload Button Bring up blank screen

### ISSUE THREAD

**Issue by mkawah** [benbalter/wp-document-revisions#85]
After the "Upload New Version" button is clicked, a blank screen appears; unable to load a document onto website.
![capture67](https://cloud.githubusercontent.com/assets/17256927/13056990/34506302-d3e7-11e5-82e0-94755d0d034c.JPG)

**Comment by benbalter** [comment]
@mkawah is this problem still occurring on the latest version? If so, please re-open the issue.
