### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by benbalter** [benbalter/wp-document-revisions#90]
With:

* [Add filter to allow opt-out of WebDAV Edit Document](https://github.com/benbalter/wp-document-revisions/pull/74)
* [Filter documents from the grid view in Media, queried via Ajax](https://github.com/benbalter/wp-document-revisions/pull/78)
* [Added code to preserve file exts on revision links](https://github.com/benbalter/wp-document-revisions/pull/81), and 
* [Verify a post ID has been passed before verifying post type](https://github.com/benbalter/wp-document-revisions/pull/86)
* [Use H2 for "Feed Privacy" heading](https://github.com/benbalter/wp-document-revisions/pull/91)

/cc @jeremyfelt in case there are any other PRs that you'd like to see in the release before it goes out (thanks for all your contributions!)

**Comment by jeremyfelt** [comment]
:+1: That list looks good. I just added #91, which is another that'd be nice to include.
