### ISSUE TITLE
Small bug in widget function

### ISSUE THREAD

**Issue by NeilWJames** [benbalter/wp-document-revisions#98]
The last code line in includes/class-wp-document-revisions-front-end.php function widget (line 315 in version of 28 Aug) has the html code escaped using esc_html. 

This results in </ul></div> appearing on the screen rather than beong actioned as html.

This escape function needs to be removed and the coding standards line (e.g. line 295) included to ignore the resulting "error".

**Comment by benbalter** [comment]
@NeilWJames are you able/interested in submitting a pull request with that change? It appears https://github.com/benbalter/wp-document-revisions/blob/master/includes/class-wp-document-revisions-front-end.php#L315 is the offending line, and that once corrected, it'll need to be ignored like https://github.com/benbalter/wp-document-revisions/blob/master/includes/class-wp-document-revisions-front-end.php#L295 above.

**Comment by jeremyfelt** [comment]
It looks like this was closed via #99.
